# =============================================================================
# Quadrant export helper for feature_response_scatter
# =============================================================================
# Takes the table output from feature_response_scatter() and partitions rows
# into quadrants based on the signs of correlation_x and correlation_y, with
# optional significance filtering on the BH-adjusted q-values on either or
# both axes. Writes one CSV per non-empty quadrant.
#
# Quadrant labels are descriptive rather than positional so they survive
# response variable swaps. The labelling assumes that for both responses,
# positive correlation means "more stable / more efficient / higher value"
# — adapt the labels via the `quadrant_labels` argument if your response
# variables have a different sign convention.
#
# Usage:
#   source("R/load_all.R")
#   source("analysis/correlations/feature_response_scatter.R")
#   source("analysis/correlations/quadrant_export.R")
#
#   df  <- build_dataset("human")
#   out <- feature_response_scatter(df)
#   write_quadrant_tables(out$table, prefix = "te_vs_halflife")
#
#   # Significance-filtered (BH q < 0.05 on BOTH axes):
#   write_quadrant_tables(out$table, prefix = "te_vs_halflife_sig",
#                         q_threshold = 0.05, sig_mode = "both")
#
#   # Single-axis significance, more permissive q:
#   write_quadrant_tables(out$table, prefix = "te_vs_halflife_any",
#                         q_threshold = 0.10, sig_mode = "any")
# =============================================================================

source("R/load_all.R")

suppressPackageStartupMessages({
  library(dplyr)
  library(purrr)
})


#' Partition a feature_response_scatter table into quadrants and write CSVs.
#'
#' @param table          The table element returned by feature_response_scatter().
#' @param prefix         Filename prefix; outputs go to
#'                       OUTPUT_DIR/tables/quadrants/<prefix>_<quadrant>.csv.
#' @param q_threshold    Numeric in (0, 1) or NULL (default). If set, rows must
#'                       satisfy `sig_mode` on q_x / q_y to be included.
#' @param sig_mode       "both" (default) requires q_x < threshold AND
#'                       q_y < threshold; "any" requires either; "x_only" /
#'                       "y_only" require just that axis.
#' @param quadrant_labels Optional named vector overriding the default labels.
#'                       Names must be exactly: pp, pn, np, nn (sign of x then y).
#' @param sort_by        Column to sort within each quadrant (default
#'                       "distance_from_origin", descending).
#' @return Invisibly, a named list of tibbles keyed by quadrant filename stem.
#' @export
write_quadrant_tables <- function(table,
                                  prefix,
                                  q_threshold      = NULL,
                                  sig_mode         = c("both", "any",
                                                       "x_only", "y_only"),
                                  quadrant_labels  = NULL,
                                  sort_by          = "distance_from_origin") {

  sig_mode <- match.arg(sig_mode)

  # --- R5: guard input shape ----------------------------------------------
  required_cols <- c("variable", "correlation_x", "correlation_y",
                     "q_x", "q_y")
  missing <- setdiff(required_cols, names(table))
  if (length(missing) > 0) {
    stop("table missing expected columns: ",
         paste(missing, collapse = ", "),
         " — was this generated by feature_response_scatter()?")
  }
  if (!sort_by %in% names(table)) {
    warning("sort_by '", sort_by, "' not in table — sorting by ",
            "abs(correlation_x) + abs(correlation_y) instead")
    table$.sort <- abs(table$correlation_x) + abs(table$correlation_y)
    sort_by <- ".sort"
  }

  # --- Default quadrant labels --------------------------------------------
  # Sign convention: pp = both positive, pn = x positive y negative, etc.
  default_labels <- c(
    pp = "concordant_positive",   # both up: stabilising / translating well
    pn = "discordant_x_pos_y_neg",
    np = "discordant_x_neg_y_pos",
    nn = "concordant_negative"    # both down: destabilising / translating poorly
  )
  if (!is.null(quadrant_labels)) {
    if (!all(c("pp", "pn", "np", "nn") %in% names(quadrant_labels))) {
      stop("quadrant_labels must have names: pp, pn, np, nn")
    }
    labels <- quadrant_labels[c("pp", "pn", "np", "nn")]
  } else {
    labels <- default_labels
  }

  # --- Significance filter ------------------------------------------------
  filtered <- table
  if (!is.null(q_threshold)) {
    filtered <- filtered |>
      dplyr::filter(switch(
        sig_mode,
        both    = q_x < q_threshold & q_y < q_threshold,
        any     = q_x < q_threshold | q_y < q_threshold,
        x_only  = q_x < q_threshold,
        y_only  = q_y < q_threshold
      ))
  }

  # --- Quadrant assignment (treat zero as positive to avoid empty bucket) -
  filtered <- filtered |>
    dplyr::mutate(
      quadrant = dplyr::case_when(
        correlation_x >= 0 & correlation_y >= 0 ~ labels[["pp"]],
        correlation_x >= 0 & correlation_y <  0 ~ labels[["pn"]],
        correlation_x <  0 & correlation_y >= 0 ~ labels[["np"]],
        correlation_x <  0 & correlation_y <  0 ~ labels[["nn"]]
      )
    )

  # --- R8: write to OUTPUT_DIR/tables/quadrants/ --------------------------
  out_dir <- file.path(OUTPUT_DIR, "tables", "quadrants")
  dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

  results <- list()

  for (lbl in unname(labels)) {
    sub <- filtered |>
      dplyr::filter(quadrant == lbl) |>
      dplyr::arrange(dplyr::desc(.data[[sort_by]]))

    fname <- file.path(out_dir, sprintf("%s_%s.csv", prefix, lbl))

    if (nrow(sub) == 0) {
      message("  empty:    ", lbl, " (no rows after filtering)")
      results[[lbl]] <- sub
      next
    }

    write.csv(sub, fname, row.names = FALSE)
    message("  written:  ", basename(fname), "  (", nrow(sub), " rows)")
    results[[lbl]] <- sub
  }

  # --- Sidecar: summary of counts per quadrant ----------------------------
  summary_tbl <- tibble::tibble(
    quadrant = unname(labels),
    n        = vapply(results, nrow, integer(1))
  )
  if (!is.null(q_threshold)) {
    summary_tbl$q_threshold <- q_threshold
    summary_tbl$sig_mode    <- sig_mode
  }
  write.csv(
    summary_tbl,
    file.path(out_dir, sprintf("%s__quadrant_counts.csv", prefix)),
    row.names = FALSE
  )

  invisible(results)
}


# -----------------------------------------------------------------------------
# Runner — example use
# -----------------------------------------------------------------------------

if (sys.nframe() == 0 || identical(environment(), globalenv())) {

  # Lazy-load the scatter so quadrant_export.R can stand alone if needed
  if (!exists("feature_response_scatter", mode = "function")) {
    source("analysis/correlations/feature_response_scatter.R")
  }

  df  <- build_dataset("human")
  out <- feature_response_scatter(df)

  message("\nAll features:")
  write_quadrant_tables(out$table, prefix = "te_vs_halflife")

  message("\nSignificant on both axes (q < 0.05):")
  write_quadrant_tables(out$table, prefix = "te_vs_halflife_sig_both",
                        q_threshold = 0.05, sig_mode = "both")

  message("\nSignificant on either axis (q < 0.10):")
  write_quadrant_tables(out$table, prefix = "te_vs_halflife_sig_any",
                        q_threshold = 0.10, sig_mode = "any")

  message("\nQuadrant exports complete. See: ",
          file.path(OUTPUT_DIR, "tables", "quadrants"))
}
